/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  3636: {
    HashedTimelock: {
      address: "0xecb1b35da47d2c9dbfd08158637ab1e176779c35",
      abi: [
        {
          type: "function",
          name: "calculateBounty",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getContract",
          inputs: [
            {
              name: "_contractId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "hashlock",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "timelock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "withdrawn",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "refunded",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "preimage",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "haveContract",
          inputs: [
            {
              name: "_contractId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "exists",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "newContract",
          inputs: [
            {
              name: "_receiver",
              type: "address",
              internalType: "address payable",
            },
            {
              name: "_hashlock",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "_timelock",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "contractId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "refund",
          inputs: [
            {
              name: "_contractId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [
            {
              name: "_contractId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "_preimage",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawWithBounty",
          inputs: [
            {
              name: "_contractId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "_preimage",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "LogHTLCNew",
          inputs: [
            {
              name: "contractId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "sender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "receiver",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "hashlock",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "timelock",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "LogHTLCRefund",
          inputs: [
            {
              name: "contractId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "LogHTLCWithdraw",
          inputs: [
            {
              name: "contractId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts;
